
vscode:
  extensions:
    - streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker-portuguese-brazilian
    - yzhang.markdown-all-in-one
    - DavidAnson.vscode-markdownlint
    - Gruntfuggly.todo-tree
